name: Craft博客发布任务

on:
  push:
    branches: [master]

jobs:
  CheckOutAndUpload:
    runs-on: ubuntu-latest

    steps:
      - name: 检出分支
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      
      - name: 设置 node 环境
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
          architecture: x64
          cache: npm

      - name: 安装依赖
        run: npm i

      - name: 运行上传脚本
        uses: actions/github-script@v5
        env:
          COS_SECRET_ID: ${{secrets.COS_SECRET_ID}}
          COS_SECRET_KEY: ${{secrets.COS_SECRET_KEY}}
          COS_BUCKET: ${{secrets.COS_BUCKET}}
          COS_REGION: ${{secrets.COS_REGION}}
          GIT_HUB_TOKEN: ${{secrets.GIT_HUB_TOKEN}}
          GIT_HUB_BRANCH: ${{secrets.GIT_HUB_BRANCH}}
          GIT_HUB_REPO: ${{secrets.GIT_HUB_REPO}}
          GIT_HUB_OWNER: ${{secrets.GIT_HUB_OWNER}}
        with:
          script: |
            const script = require('./publish.js')
            await script({github, context, core})


